### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by DuduStyle** [Blubiubiu/webpack4_mpa_demo#1]
![image](https://user-images.githubusercontent.com/31200868/48172560-4aa98780-e33b-11e8-847d-7194aa946505.png)

**Comment by Blubiubiu** [comment]
fir, 确保您使用的是master代码
sec, 您可以尝试使用npm run test,  如果希望本地调试，可以在package.json中配置(readme会更新配置方法)

**Comment by DuduStyle** [comment]
是master没错
