### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by kailong321200875** [Blubiubiu/webpack4_mpa_demo#12]
1.打包之后打开index.html， 控制台报错 Uncaught SyntaxError: Unexpected token <
2.在index.js里面引入的index.scss文件没有效果。样式没有出来

**Comment by Blubiubiu** [comment]
感谢您的使用，可能在之前并没有说清楚打包与开发流程，您可以尝试删除node_modules文件，重新install，并参照v1.0.7使用本地开发或生产打包的命令，为您造成不便请谅解！

**Comment by Blubiubiu** [comment]
感谢您的使用，问题已经更正。您可以重新拉取项目，重新install项目插件，并参考v1.0.7文档使用。如果在以后的使用过程中，发现其他问题，欢迎您第一时间提交issues！
