### ISSUE TITLE
打包之后跳转的HTML路径不对了。404

### ISSUE THREAD

**Issue by kailong321200875** [Blubiubiu/webpack4_mpa_demo#13]
1.打包之后跳转的HTML路径不对了。404
2.图片的路径问题，开发环境下展示没有问题，打包完之后，图片。背景图就展示不出来了。只有内联的图片能展示出来

**Comment by Blubiubiu** [comment]
感谢您的使用，您的问题已于v1.0.8版本得到修正。如果您在之后的使用过程中仍遇到问题，麻烦您继续提交issues，用来帮助您和更多人！

**Comment by Blubiubiu** [comment]
感谢您的使用，您的问题已于v1.0.8版本得到修复。如果您在后续的使用过程中仍遇到问题，请您继续提出issues，我会第一时间为您解决！

**Comment by kailong321200875** [comment]
1.内联图片出不来了。
`<div style="width: 300px;height: 300px;background-image: url(../../assets/images/time.jpg);"></div>`
2.icons引入失败，没办法使用字体图标

**Comment by kailong321200875** [comment]
> 感谢您的使用，您的问题已于v1.0.8版本得到修复。如果您在后续的使用过程中仍遇到问题，请您继续提出issues，我会第一时间为您解决！

我要重新提一个issues吗

**Comment by Blubiubiu** [comment]
第一个Q：这个问题确实如此，但我并不推荐这样使用，所以并不打算对此给出修改。对于css还是建议您写在css文件中，如果一定要这样使用，您可以在webpack.rules.conf.js中修改html-loader?interpolate!./your-file.html，并且在html中这样使用\<div style="background-image: url('${require(`../../content/images/logo.png`)}')">，（具体可以查看html-loader文档）这或许更加麻烦了不是吗？
第二个Q：无法引用字体图标是因为没有导入相应的loader，这个工具只是为了方便您搭建多页面应用，至于您需要的插件可能还需要自己添加
{  
test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
loader: 'url-loader'
}

**Comment by kailong321200875** [comment]
> 第一个Q：这个问题确实如此，但我并不推荐这样使用，所以并不打算对此给出修改。对于css还是建议您写在css文件中，如果一定要这样使用，您可以在webpack.rules.conf.js中修改html-loader?interpolate!./your-file.html，并且在html中这样使用<div style="background-image: url('${require(`../../content/images/logo.png`)}')">，（具体可以查看html-loader文档）这或许更加麻烦了不是吗？
> 第二个Q：无法引用字体图标是因为没有导入相应的loader，这个工具只是为了方便您搭建多页面应用，至于您需要的插件可能还需要自己添加
> {
> test: /.(woff2?|eot|ttf|otf)(?.*)?$/,
> loader: 'url-loader'
> }

好。那我有问题在请教你
