### ISSUE TITLE
修改html文件，页面不会刷新。

### ISSUE THREAD

**Issue by DemoorBug** [Blubiubiu/webpack4_mpa_demo#5]
我找到了一个解决方案就是去掉`hot: true`，但是这样会导致css无法热更新，你有更好的办法吗，还是说就用F5刷新最好？

**Comment by Blubiubiu** [comment]
您现在可以根据1.0.5的改动来添加html热更新了

**Comment by DemoorBug** [comment]
这个`raw-loader`和`html-loader`一起使用会有bug, 去除`html-loader`后页面引入的图片路径就不会处理。我下载了你的代码，也有同样的问题！！

**Comment by DemoorBug** [comment]
我找到了解决方法
```js
{
  test: /\.html$/,
  use: [
    {
      loader: 'html-loader?config=raw-loader',
      options: {
        attrs: ['img:src']
      }
    },
  ]
}
```
不过这种方法只能做到刷新页面，热更新还是不行，不过好像找不到更优的方案了

**Comment by DemoorBug** [comment]
还有`index.html`文件引入的时候要区分开发环境，不然打包的时候会把html打包到js中
```js
if (process.env.NODE_ENV !== 'production') {
  require('./index.html');
}
```

**Comment by Blubiubiu** [comment]
感谢您的建议，已经做出修改，如果您在使用中还有好的意见或建议，可以继续提issues或者pr，再次感谢支持...
