### ISSUE TITLE
Cannot apply update. Need to do a full reload!

### ISSUE THREAD

**Issue by canfoo** [Blubiubiu/webpack4_mpa_demo#7]
修改js文件，热更新报了警告："Cannot apply update. Need to do a full reload!"

**Comment by Blubiubiu** [comment]
并未发现你所说的问题，建议查看webpack版本，或者重新下载依赖...如果还是不行，麻烦给出更多信息帮助我解决你的问题，谢谢

**Comment by canfoo** [comment]
已发现问题了，thx
