### ISSUE TITLE
作为小白的疑惑。

### ISSUE THREAD

**Issue by YangPengFe1** [Blubiubiu/webpack4_mpa_demo#8]
看了整个工程，觉得很高大上，非常之想学习 但是不知道从哪里开始，我想了解一下，这样的webpack工程架构，适用于哪种场景下的项目？大佬可否，细聊一下

**Comment by Blubiubiu** [comment]
感谢支持......
此工程出发点为项目需求制作app的分享页，分析后发现其实只是一些简单的web页与一些经常需要切换内容的场景，使用框架（vue,react,ng等）并不是那么必要，平白无故增加了体积确并没有多少的提升，且总是使用框架让本身的原生技术都有些遗忘了。
我们的页面多是进行简单的dom操作或者特殊的活动页，页面之间的耦合并不高，虽然不使用框架，但是使项目工程化却是有必要的，所以有了此demo专门用来处理多页面问题。
当然如果您喜欢使用框架，只要引入相应的loader进行一些修改即可，不过我在搭建此项目时就是为了不使用它们，所以就不在demo里做了。

**Comment by Blubiubiu** [comment]
如果您想学习，只需要去webpack官网认真查看文档，相信您在阅读后会对此项目有更好的认识，期待您为此项目提供pr哦...[多多捂脸]

**Comment by YangPengFe1** [comment]
感谢回复，谢谢。哈哈，等着我的pr。
